### ISSUE TITLE
Another case of "kotlin.NotImplementedError: An operation is not implemented: something went wrong"

### ISSUE THREAD

**Issue by humpfhumpf** [erosb/json-sKema#109]
Another case of "kotlin.NotImplementedError" with a simple JSON Schema, mixing "required" and "additionalProperties" (at different levels).

The JSON to validate contains "codeError" instead of "code" (3 times) in a 2 levels structure.

Tested with:
* json-sKema 0.16.0
* JDK 17

Exception content is:
```
Exception in thread "main" kotlin.NotImplementedError: An operation is not implemented: something went wrong: {
  "aaa": {
    "aaa1": {
      "codeERROR": "AAA1"
    },
    "aaa2": {
      "codeERROR": "AAA2"
    }
  },
  "bbb": {
    "codeERROR": "BBB"
  }
} vs {
  "aaa1": {
    "codeERROR": "AAA1"
  },
  "aaa2": {
    "codeERROR": "AAA2"
  }
}
	at com.github.erosb.jsonsKema.AggregatingValidationFailure.join$json_sKema(ValidationFailure.kt:67)
	at com.github.erosb.jsonsKema.DefaultValidator.accumulate(Validator.kt:720)
	at com.github.erosb.jsonsKema.DefaultValidator.accumulate(Validator.kt:165)
	at com.github.erosb.jsonsKema.SchemaVisitor.visitCompositeSchema(SchemaVisitor.kt:71)
	at com.github.erosb.jsonsKema.DefaultValidator.visitCompositeSchema(Validator.kt:271)
	at com.github.erosb.jsonsKema.DefaultValidator.visitCompositeSchema(Validator.kt:165)
	at com.github.erosb.jsonsKema.SchemaVisitor.internallyVisitCompositeSchema$json_sKema(SchemaVisitor.kt:55)
	at com.github.erosb.jsonsKema.CompositeSchema.accept(Schema.kt:26)
	at com.github.erosb.jsonsKema.DefaultValidator.validate(Validator.kt:258)
	at fdj.App.main(App.java:71)
```

Java program to show the issue:

```java
import com.github.erosb.jsonsKema.*;

public class App 
{
    public static void main( String[] args )
    {
        JsonValue schemaJson = new JsonParser("""
        {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "aaa": {
              "type": "object",
              "properties": {
                "aaa1": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                },
                "aaa2": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              },
              "required": [
                "aaa1",
                "aaa2"
              ]
            },
            "bbb": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          }
        }
        """).parse();
        Schema schema = new SchemaLoader(schemaJson).load();
        Validator validator = Validator.forSchema(schema);
        JsonValue instance = new JsonParser("""
        {
            "aaa": {
                "aaa1": {
                    "codeERROR": "AAA1"
                },
                "aaa2": {
                    "codeERROR": "AAA2"
                }
            },
            "bbb": {
                "codeERROR": "BBB"
            }
        }
        """).parse();

        ValidationFailure failure = validator.validate(instance);
        System.out.println(failure);
    }
}
```

**Comment by erosb** [comment]
Thank you @humpfhumpf for the reproducer, very useful!

**Comment by erosb** [comment]
Thanks again @humpfhumpf , I released a bugfix in version `0.17.0` (already available on maven central).
