### ISSUE TITLE
supports tuple validation mode for items in array object

### ISSUE THREAD

**Issue by sacrex** [erosb/json-sKema#27]
Hello, your work is very good and has solved many of my problems, especially for error reports, I haven't found a good way to handle them from other jsonschema projects。I hope you can support the tuple mode of array.items. Thank you very much。

Input some json below, it throw error.
json code:
`
{
  "type": "array",
  "title": "array desc",
  "items": [
     {"type": "object", "title": "some obj"}
   ]
}
`

cause
`
Caused by: kotlin.NotImplementedError: An operation is not implemented.
	at com.github.erosb.jsonsKema.SchemaLoader.doLoadSchema(SchemaLoader.kt:428)
	at com.github.erosb.jsonsKema.SchemaLoader.loadChild$json_sKema(SchemaLoader.kt:515)
	at com.github.erosb.jsonsKema.SchemaLoader$createCompositeSchema$1$1$ctx$1.invoke(SchemaLoader.kt:452)
	at com.github.erosb.jsonsKema.SchemaLoader$createCompositeSchema$1$1$ctx$1.invoke(SchemaLoader.kt:450)
	at com.github.erosb.jsonsKema.ItemsKt$itemsSchemaLoader$1.invoke(Items.kt:10)
	at com.github.erosb.jsonsKema.ItemsKt$itemsSchemaLoader$1.invoke(Items.kt:8)
	at com.github.erosb.jsonsKema.SchemaLoader$createCompositeSchema$1.invoke(SchemaLoader.kt:475)
	at com.github.erosb.jsonsKema.SchemaLoader$createCompositeSchema$1.invoke(SchemaLoader.kt:447)
	at com.github.erosb.jsonsKema.SchemaLoader.enterScope(SchemaLoader.kt:176)
	at com.github.erosb.jsonsKema.SchemaLoader.createCompositeSchema(SchemaLoader.kt:447)
`

**Comment by erosb** [comment]
Hello @sacrex , thank you for your kind words. Tuple mode validation was removed in `draft2020-12` version of json schema and was substituted by [`prefixItems`](https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.3.1.1). Hope this helps.

**Comment by sacrex** [comment]
Thank you
