### ISSUE TITLE
java.lang.IllegalStateException: Unable to load a schema for URI : http://json-schema.org/draft-07/schema#

### ISSUE THREAD

**Issue by bsanchezb** [erosb/json-sKema#87]
Hello,

Since version 0.11.0, there is a regression on loading a schema, containing a "$schema" header:

```
{
	"$schema": "http://json-schema.org/draft-07/schema#",
        ...
}
```

I receive the following exception:

```
java.lang.IllegalStateException: Unable to load a schema for URI : http://json-schema.org/draft-07/schema#
        at eu.europa.esig.jws.AbstractJWSUtils$ResourceSchemaClient.get(AbstractJWSUtils.java:369)
        at eu.europa.esig.jws.AbstractJWSUtils$ResourceSchemaClient.getParsed(AbstractJWSUtils.java:375)
        at com.github.erosb.jsonsKema.SchemaLoader.findVocabulariesInMetaSchema(SchemaLoader.kt:198)
        at com.github.erosb.jsonsKema.SchemaLoader.<init>(SchemaLoader.kt:190)
        at ...

java.lang.IllegalStateException: Unable to load a schema for URI : http://json-schema.org/draft-07/schema#
        at eu.europa.esig.jws.AbstractJWSUtils$ResourceSchemaClient.get(AbstractJWSUtils.java:369)
        at eu.europa.esig.jws.AbstractJWSUtils$ResourceSchemaClient.getParsed(AbstractJWSUtils.java:375)
        at com.github.erosb.jsonsKema.SchemaLoader.findVocabulariesInMetaSchema(SchemaLoader.kt:198)
        at com.github.erosb.jsonsKema.SchemaLoader.<init>(SchemaLoader.kt:190)
```

Is there a workaround for the issue or is it possible to fix in the new version?

Best regards,
Aleksandr

**Comment by erosb** [comment]
Hello @bsanchezb , at the first glance: I strongly advise not using any draft-07 schema with this library, since this implements draft version 2020-12 (which isn't compatible with draft-07).

If you really need to validate draft-07 schemas, then you can either [pre-register](https://github.com/erosb/json-sKema?tab=readme-ov-file#pre-registering-schemas-by-uri-before-schema-loading) it, or maybe it works if you just remove the trailing # character.

**Comment by bsanchezb** [comment]
Hello @erosb ,

Thank you for the answer. The https://github.com/everit-org/json-schema/ library has been deprecated, that is why we were forced to migrate to the current library.

Removing of # character from the schema itself is not possible, as we are using official json schemas provided within [ETSI TS 119 182-1](https://www.etsi.org/deliver/etsi_ts/119100_119199/11918201/01.01.01_60/ts_11918201v010101p.pdf) standard for JAdES signatures. Any custom modifications within the schema are not advisable.

Nevertheless, the fix with registering the original draft-07 schema seems working! Thank you for the tip.

Best regards,
Aleksandr

**Comment by erosb** [comment]
Hello @bsanchezb I tried to add a reproducer for this issue, but this test passes: https://github.com/erosb/json-sKema/commit/446a7d27313f51268de13f6fbec4b04d73d7661e

Is the issue still reproducible on your side? I looked into [this class](https://github.com/esig/dss/blob/master/specs-jws/src/main/java/eu/europa/esig/jws/AbstractJWSUtils.java#L368) but I can't see anything in its current version that can cause this issue.

**Comment by erosb** [comment]
Hello @bsanchezb do you still face this issue? I think the reproducer test used to fail for a while, but only with java 8. Recently the failure disappeared even from the java 8 builds. What is the situation on your side? By the way, do you see any chance to upgrade to a newer java version, in the foreseeable future?
